version: '3.8'

services:
  # 1. Frontend Container (HTTPD)
  frontend:
    image: httpd:latest
    container_name: frontend_web
    ports:
      - "8080:80" 
    volumes:
      
      - ./frontend/index.html:/usr/local/apache2/htdocs/index.html
    networks:
      - frontend_net
    depends_on:
      - backend 

  # 2. Backend Container (Flask)
  backend:
    image: ranaahmed2/flask-app:0.1 
    container_name: backend_api
    networks:
      - frontend_net 
      - backend_net
    depends_on:
      - database 

  # 3. Database Container (MariaDB)
  database:
    image: mariadb:latest
    container_name: db_server
    environment:
      MYSQL_ROOT_PASSWORD: your_secret_password
    networks:
      - backend_net 
    restart: unless-stopped

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

